import type { IngredientCategory } from "./types";

/**
 * 知识库 mock 数据（V1 演示用）
 * 真实环境替换为后台知识库（PRD §17.6）查询：
 * 配料库 / 添加剂库 / 过敏原库，每条含来源与更新时间。
 */

export interface IngredientKnowledge {
  /** 标准名称（匹配 key） */
  name: string;
  aliases?: string[];
  category: IngredientCategory;
  /** 一句话解释 */
  oneLiner: string;
  /** 加工性质说明 */
  processingNature?: string;
  /** 主要用途 */
  purpose: string;
  /** 详细说明（第二层） */
  detail?: string;
  /** 潜在过敏原类别 */
  allergens?: string[];
  /** 注意事项（食用/摄入需留意的点） */
  caution?: string;
  /** 不适宜/关注人群 */
  audience?: string;
  /** 数据来源 */
  source: string;
  updatedAt: string;
}

export interface AdditiveKnowledge {
  name: string;
  aliases?: string[];
  insE: string;
  type: string;
  /** 一句话解释 */
  oneLiner: string;
  /** 主要用途 */
  purpose: string;
  /** 常见应用 */
  commonUses: string;
  /** 为什么添加 */
  whyAdded?: string;
  /** 安全性说明 */
  safetyNote: string;
  /** 注意事项 */
  caution: string;
  /** 关注人群 */
  audience: string;
  /** 使用范围 */
  usageScope?: string;
  source: string;
  updatedAt: string;
}

/** 配料知识库 */
export const INGREDIENT_KB: Record<string, IngredientKnowledge> = {
  小麦粉: {
    name: "小麦粉",
    aliases: ["面粉"],
    category: "natural",
    oneLiner: "由小麦研磨而成的粉末状谷物原料。",
    processingNature: "基础原料",
    purpose: "提供结构、口感和碳水化合物，是面包、糕点等的主料。",
    detail: "根据研磨精度分为高筋、中筋、低筋等类型。含麸质蛋白。",
    caution: "含麸质蛋白，麸质敏感或乳糜泻人群需避免。",
    audience: "麸质过敏、乳糜泻人群不适宜。",
    allergens: ["麸质"],
    source: "GB/T 1355 / OFF",
    updatedAt: "2026-08-28",
  },
  白砂糖: {
    name: "白砂糖",
    category: "natural",
    oneLiner: "从甘蔗或甜菜中提取精制而成的蔗糖。",
    processingNature: "基础原料",
    purpose: "提供甜味、促进褐变反应，并帮助食品保持质地。",
    detail: "属添加糖类。配料表顺序反映加入量排序。",
    caution: "属添加糖，摄入过多可能影响血糖与体重，建议控制摄入量。",
    audience: "糖尿病患者及控糖人群应留意摄入量。",
    source: "GB/T 317 / OFF",
    updatedAt: "2026-08-28",
  },
  食用植物油: {
    name: "食用植物油",
    aliases: ["植物油"],
    category: "natural",
    oneLiner: "从植物种子或果实中压榨或浸出的油脂。",
    processingNature: "基础原料",
    purpose: "提供脂肪、口感与香气，是煎炸和烘焙的重要原料。",
    detail: "常见种类包括菜籽油、大豆油、棕榈油等，可能为调和油。",
    caution: "部分产品可能为棕榈油等高饱和脂肪来源，需控制总油脂摄入。",
    audience: "需控制脂肪摄入人群应留意。",
    source: "GB 2716 / OFF",
    updatedAt: "2026-08-26",
  },
  乳粉: {
    name: "乳粉",
    aliases: ["奶粉"],
    category: "natural",
    oneLiner: "将牛乳浓缩干燥制成的粉末状乳制品。",
    processingNature: "基础原料",
    purpose: "提供乳蛋白、乳脂与乳糖，常用于烘焙、饮料和婴幼儿配方。",
    detail: "乳粉属于乳及乳制品。对乳糖不耐受或乳蛋白过敏人群需留意。",
    caution: "含乳糖与乳蛋白。",
    audience: "乳糖不耐受、乳蛋白过敏人群不宜。",
    allergens: ["乳"],
    source: "GB 19644 / OFF",
    updatedAt: "2026-08-27",
  },
  麦芽糖浆: {
    name: "麦芽糖浆",
    category: "processed",
    oneLiner: "由淀粉部分水解制成的甜味糖浆。",
    processingNature: "加工原料",
    purpose: "提供甜味和保湿性，帮助食品保持柔软质地。",
    detail: "属于淀粉糖浆类，甜度低于蔗糖。",
    caution: "属糖类，升糖较快，需控制摄入量。",
    audience: "糖尿病患者及控糖人群应留意。",
    source: "GB/T 20883 / OFF",
    updatedAt: "2026-08-25",
  },
  麦芽糊精: {
    name: "麦芽糊精",
    category: "processed",
    oneLiner: "淀粉部分水解得到的短链多糖。",
    processingNature: "加工原料",
    purpose: "作为填充剂、增稠剂和载体，帮助改善食品质地。",
    detail: "由淀粉酶解制成，可来源于玉米、小麦等。若来源于小麦需留意麸质。",
    caution: "升糖指数较高，可能来源于含麸质谷物（如小麦）。",
    audience: "糖尿病患者、麸质敏感人群（视原料）应留意。",
    allergens: ["麸质（视原料）"],
    source: "GB/T 20882 / OFF",
    updatedAt: "2026-08-24",
  },
  食盐: {
    name: "食盐",
    aliases: ["盐"],
    category: "natural",
    oneLiner: "主要成分为氯化钠的调味原料。",
    processingNature: "基础原料",
    purpose: "提供咸味、增强风味并起防腐作用。",
    detail: "不同产品可能含碘或抗结剂。",
    caution: "过量摄入钠与高血压风险相关。",
    audience: "高血压、肾病等需限钠人群应留意。",
    source: "GB/T 5461 / OFF",
    updatedAt: "2026-08-28",
  },
  燕麦片: {
    name: "燕麦片",
    category: "natural",
    oneLiner: "由燕麦籽粒压制成的片状谷物。",
    processingNature: "基础原料",
    purpose: "提供膳食纤维、蛋白质和碳水化合物。",
    detail: "燕麦本身不含麸质，但加工过程可能交叉污染，相关人群需确认包装声明。",
    caution: "本身不含麸质，但加工过程可能交叉污染。",
    audience: "乳糜泻人群应选择明确标注无麸质的产品。",
    allergens: ["麸质（交叉污染可能）"],
    source: "OFF",
    updatedAt: "2026-08-28",
  },
  水: {
    name: "水",
    category: "natural",
    oneLiner: "饮料与液体食品的基础介质。",
    processingNature: "基础原料",
    purpose: "作为溶剂和主体成分，溶解其他配料。",
    detail: "多为处理后水源，成分以水为主。",
    source: "GB 19298 / OFF",
    updatedAt: "2026-08-28",
  },
  // ===== 高频配料扩展（本地知识库 L1，命中 0 token）=====
  米粉: {
    name: "米粉",
    aliases: ["大米粉"],
    category: "natural",
    oneLiner: "由大米研磨而成的粉末状谷物原料。",
    processingNature: "基础原料",
    purpose: "提供淀粉质与米香，用于米制品、糕点与裹粉。",
    detail: "本身不含麸质，可用于无麸质烘焙。",
    source: "GB/T 1354 / OFF",
    updatedAt: "2026-08-31",
  },
  全麦粉: {
    name: "全麦粉",
    aliases: ["全麦面粉"],
    category: "natural",
    oneLiner: "保留麦麸与胚芽的小麦全粉。",
    processingNature: "基础原料",
    purpose: "提供膳食纤维与 B 族维生素，口感较粗糙。",
    detail: "含麸质蛋白，麸质敏感人群需留意。",
    allergens: ["麸质"],
    source: "GB/T 21122 / OFF",
    updatedAt: "2026-08-31",
  },
  玉米淀粉: {
    name: "玉米淀粉",
    aliases: ["玉米生粉"],
    category: "processed",
    oneLiner: "由玉米提取的淀粉。",
    processingNature: "加工原料",
    purpose: "用于增稠、裹粉与烘焙。",
    detail: "玉米来源；对玉米过敏人群较为少见。",
    source: "GB/T 8885 / OFF",
    updatedAt: "2026-08-31",
  },
  马铃薯淀粉: {
    name: "马铃薯淀粉",
    aliases: ["土豆淀粉"],
    category: "processed",
    oneLiner: "由马铃薯提取的淀粉。",
    processingNature: "加工原料",
    purpose: "吸水性好，适合勾芡、裹粉与烘焙。",
    source: "GB/T 8884 / OFF",
    updatedAt: "2026-08-31",
  },
  木薯淀粉: {
    name: "木薯淀粉",
    category: "processed",
    oneLiner: "由木薯块根提取的淀粉。",
    processingNature: "加工原料",
    purpose: "提供弹糯口感，常用于珍珠、糕点和甜品。",
    source: "GB/T 29343 / OFF",
    updatedAt: "2026-08-31",
  },
  糯米粉: {
    name: "糯米粉",
    category: "natural",
    oneLiner: "由糯米研磨而成的粉末。",
    processingNature: "基础原料",
    purpose: "用于汤圆、年糕、麻薯等糯米制品。",
    source: "GB 2715 / OFF",
    updatedAt: "2026-08-31",
  },
  荞麦粉: {
    name: "荞麦粉",
    category: "natural",
    oneLiner: "由荞麦籽研磨的粉，本身不含麸质。",
    processingNature: "基础原料",
    purpose: "提供独特香气，常用于荞麦面与烘焙。",
    detail: "加工过程可能交叉污染麸质，敏感人群需确认包装声明。",
    allergens: ["麸质（交叉污染可能）"],
    source: "GB/T 35028 / OFF",
    updatedAt: "2026-08-31",
  },
  黑麦粉: {
    name: "黑麦粉",
    category: "natural",
    oneLiner: "由黑麦研磨的谷物粉。",
    processingNature: "基础原料",
    purpose: "提供深色麦香与更多膳食纤维。",
    allergens: ["麸质"],
    source: "GB 2715 / OFF",
    updatedAt: "2026-08-31",
  },
  藜麦: {
    name: "藜麦",
    category: "natural",
    oneLiner: "原产南美安第斯地区的古老谷物。",
    processingNature: "基础原料",
    purpose: "提供蛋白质、膳食纤维与矿物质。",
    source: "OFF",
    updatedAt: "2026-08-31",
  },
  葡萄糖: {
    name: "葡萄糖",
    category: "natural",
    oneLiner: "单糖，天然存在于水果与蜂蜜中。",
    processingNature: "基础原料",
    purpose: "提供甜味与能量，易被人体吸收。",
    source: "GB 15203 / OFF",
    updatedAt: "2026-08-31",
  },
  葡萄糖浆: {
    name: "葡萄糖浆",
    category: "processed",
    oneLiner: "淀粉水解制成的糖浆。",
    processingNature: "加工原料",
    purpose: "提供甜味、保湿并防止结晶。",
    caution: "属糖类，升糖较快。",
    audience: "糖尿病患者及控糖人群应留意。",
    source: "GB/T 20885 / OFF",
    updatedAt: "2026-08-31",
  },
  果葡糖浆: {
    name: "果葡糖浆",
    category: "processed",
    oneLiner: "由淀粉制取的葡萄糖与果糖混合糖浆。",
    processingNature: "加工原料",
    purpose: "甜度高，常用于饮料、冷饮与果酱。",
    detail: "果糖含量较高，关注血糖的人群可留意摄入量。",
    caution: "果糖含量较高，过量摄入可能增加代谢负担。",
    audience: "糖尿病患者、痛风及需控糖人群应留意。",
    source: "GB/T 26762 / OFF",
    updatedAt: "2026-08-31",
  },
  蜂蜜: {
    name: "蜂蜜",
    category: "natural",
    oneLiner: "蜜蜂采集花蜜酿制的天然甜味物质。",
    processingNature: "基础原料",
    purpose: "提供甜味与独特风味。",
    detail: "1 岁以下婴幼儿不宜食用（肉毒杆菌风险）。",
    caution: "可能含肉毒杆菌芽孢。",
    audience: "1 岁以下婴幼儿不宜食用。",
    source: "GB 14963 / OFF",
    updatedAt: "2026-08-31",
  },
  红糖: {
    name: "红糖",
    category: "natural",
    oneLiner: "未经高度精制的蔗糖。",
    processingNature: "基础原料",
    purpose: "提供甜味，带有焦糖色泽与风味。",
    source: "QB/T 4561 / OFF",
    updatedAt: "2026-08-31",
  },
  冰糖: {
    name: "冰糖",
    category: "natural",
    oneLiner: "由蔗糖结晶精制而成的糖。",
    processingNature: "基础原料",
    purpose: "提供甜味，常用于炖煮与饮品。",
    source: "GB/T 35883 / OFF",
    updatedAt: "2026-08-31",
  },
  乳糖: {
    name: "乳糖",
    category: "processed",
    oneLiner: "牛奶中的天然双糖。",
    processingNature: "加工原料",
    purpose: "用于乳制品、糖果与片剂辅料。",
    detail: "乳糖不耐受人群需留意摄入量。",
    caution: "乳糖不耐受人群摄入后可能引起腹胀、腹泻。",
    audience: "乳糖不耐受人群不宜。",
    allergens: ["乳"],
    source: "GB 25595 / OFF",
    updatedAt: "2026-08-31",
  },
  海藻糖: {
    name: "海藻糖",
    category: "natural",
    oneLiner: "天然存在的双糖，具保湿与抗冻作用。",
    processingNature: "基础原料",
    purpose: "提供甜味，帮助保持食品质地。",
    source: "GB/T 23529 / OFF",
    updatedAt: "2026-08-31",
  },
  低聚果糖: {
    name: "低聚果糖",
    category: "processed",
    oneLiner: "由果糖聚合而成的低聚糖，属益生元。",
    processingNature: "加工原料",
    purpose: "促进肠道益生菌生长，具温和甜味。",
    source: "GB/T 23528 / OFF",
    updatedAt: "2026-08-31",
  },
  菊粉: {
    name: "菊粉",
    category: "natural",
    oneLiner: "从菊苣等植物提取的膳食纤维。",
    processingNature: "基础原料",
    purpose: "作为膳食纤维来源，也用于糖分替代。",
    source: "GB 25541 / OFF",
    updatedAt: "2026-08-31",
  },
  黄油: {
    name: "黄油",
    category: "natural",
    oneLiner: "从牛奶中分离出的乳脂制品。",
    processingNature: "基础原料",
    purpose: "提供浓郁奶香与酥脆口感。",
    allergens: ["乳"],
    caution: "饱和脂肪含量较高。",
    audience: "乳制品过敏人群、需控制饱和脂肪摄入人群应留意。",
    source: "GB 19646 / OFF",
    updatedAt: "2026-08-31",
  },
  人造奶油: {
    name: "人造奶油",
    category: "processed",
    oneLiner: "以植物油为主制成的乳脂替代品。",
    processingNature: "加工原料",
    purpose: "用于烘焙、涂抹与裱花。",
    detail: "部分产品可能含氢化植物油，留意反式脂肪。",
    caution: "部分产品可能含氢化植物油（反式脂肪）。",
    audience: "关注反式脂肪摄入人群应留意。",
    allergens: ["乳（可能）"],
    source: "GB 15196 / OFF",
    updatedAt: "2026-08-31",
  },
  起酥油: {
    name: "起酥油",
    category: "processed",
    oneLiner: "经氢化或调配的油脂，用于起酥。",
    processingNature: "加工原料",
    purpose: "提供酥脆分层口感。",
    detail: "留意部分氢化植物油带来的反式脂肪。",
    caution: "可能含部分氢化植物油（反式脂肪）。",
    audience: "关注反式脂肪摄入人群应留意。",
    source: "GB 15196 / OFF",
    updatedAt: "2026-08-31",
  },
  猪油: {
    name: "猪油",
    category: "natural",
    oneLiner: "从猪脂肪中提炼的油脂。",
    processingNature: "基础原料",
    purpose: "提供浓郁香气，常用于中式酥点与炒制。",
    source: "GB 10146 / OFF",
    updatedAt: "2026-08-31",
  },
  椰子油: {
    name: "椰子油",
    category: "natural",
    oneLiner: "从椰肉提取的植物油。",
    processingNature: "基础原料",
    purpose: "提供特有风味，常用于烘焙与椰子制品。",
    source: "GB 2716 / OFF",
    updatedAt: "2026-08-31",
  },
  花生油: {
    name: "花生油",
    category: "natural",
    oneLiner: "由花生压榨的植物油。",
    processingNature: "基础原料",
    purpose: "提供浓郁香味，适合炒制与油炸。",
    allergens: ["花生"],
    source: "GB 1534 / OFF",
    updatedAt: "2026-08-31",
  },
  菜籽油: {
    name: "菜籽油",
    category: "natural",
    oneLiner: "由油菜籽压榨的植物油。",
    processingNature: "基础原料",
    purpose: "用途广泛的烹调油。",
    source: "GB 1536 / OFF",
    updatedAt: "2026-08-31",
  },
  芝麻油: {
    name: "芝麻油",
    aliases: ["香油"],
    category: "natural",
    oneLiner: "由芝麻压榨的调味油。",
    processingNature: "基础原料",
    purpose: "提供独特香气，用于凉拌与调味。",
    allergens: ["芝麻"],
    source: "GB/T 8233 / OFF",
    updatedAt: "2026-08-31",
  },
  橄榄油: {
    name: "橄榄油",
    category: "natural",
    oneLiner: "由油橄榄果实压榨的植物油。",
    processingNature: "基础原料",
    purpose: "提供温和果香，适合凉拌与低温烹饪。",
    source: "GB/T 23347 / OFF",
    updatedAt: "2026-08-31",
  },
  全脂奶粉: {
    name: "全脂奶粉",
    category: "natural",
    oneLiner: "以全脂牛乳浓缩干燥制成的粉末。",
    processingNature: "基础原料",
    purpose: "提供乳蛋白、乳脂与乳糖。",
    allergens: ["乳"],
    caution: "含乳糖与较高脂肪。",
    audience: "乳糖不耐受、乳蛋白过敏人群不宜。",
    source: "GB 19644 / OFF",
    updatedAt: "2026-08-31",
  },
  脱脂奶粉: {
    name: "脱脂奶粉",
    category: "natural",
    oneLiner: "脱去大部分乳脂的奶粉。",
    processingNature: "基础原料",
    purpose: "提供乳蛋白，脂肪含量低。",
    allergens: ["乳"],
    caution: "含乳糖。",
    audience: "乳糖不耐受、乳蛋白过敏人群不宜。",
    source: "GB 19644 / OFF",
    updatedAt: "2026-08-31",
  },
  炼乳: {
    name: "炼乳",
    category: "natural",
    oneLiner: "浓缩并常加糖的乳制品。",
    processingNature: "基础原料",
    purpose: "提供浓郁奶香与甜味。",
    allergens: ["乳"],
    caution: "含糖量较高。",
    audience: "糖尿病患者及控糖人群应留意。",
    source: "GB 13102 / OFF",
    updatedAt: "2026-08-31",
  },
  奶油: {
    name: "奶油",
    category: "natural",
    oneLiner: "从牛奶中分离出的高脂乳制品。",
    processingNature: "基础原料",
    purpose: "用于打发、烘焙与饮品。",
    allergens: ["乳"],
    caution: "饱和脂肪含量较高，含乳。",
    audience: "乳制品过敏人群应留意。",
    source: "GB 19646 / OFF",
    updatedAt: "2026-08-31",
  },
  奶酪: {
    name: "奶酪",
    aliases: ["芝士"],
    category: "natural",
    oneLiner: "牛乳经发酵凝乳制成的乳制品。",
    processingNature: "基础原料",
    purpose: "提供咸香风味与乳蛋白。",
    allergens: ["乳"],
    caution: "含乳糖与钠，发酵后乳糖含量通常较低。",
    audience: "乳蛋白过敏人群不宜。",
    source: "GB 5420 / OFF",
    updatedAt: "2026-08-31",
  },
  植脂末: {
    name: "植脂末",
    aliases: ["奶精"],
    category: "processed",
    oneLiner: "以植物油、糖浆与乳蛋白等制成的粉末。",
    processingNature: "加工原料",
    purpose: "用于咖啡、奶茶等增香增滑。",
    detail: "可能含氢化植物油，留意反式脂肪。",
    caution: "可能含氢化植物油（反式脂肪），部分产品含乳蛋白。",
    audience: "关注反式脂肪摄入人群、乳蛋白过敏人群应留意。",
    allergens: ["乳（可能）"],
    source: "QB/T 4791 / OFF",
    updatedAt: "2026-08-31",
  },
  乳清蛋白: {
    name: "乳清蛋白",
    category: "processed",
    oneLiner: "从乳清中提取的蛋白质。",
    processingNature: "加工原料",
    purpose: "提供优质蛋白，常用于运动食品。",
    allergens: ["乳"],
    source: "GB 11674 / OFF",
    updatedAt: "2026-08-31",
  },
  酪蛋白: {
    name: "酪蛋白",
    category: "processed",
    oneLiner: "牛乳中的主要蛋白质。",
    processingNature: "加工原料",
    purpose: "提供蛋白与乳化稳定性。",
    allergens: ["乳"],
    source: "GB 31638 / OFF",
    updatedAt: "2026-08-31",
  },
  乳清粉: {
    name: "乳清粉",
    aliases: ["甜乳清粉"],
    category: "processed",
    oneLiner: "乳清经浓缩干燥制成的粉末，含乳糖与乳蛋白。",
    processingNature: "加工原料",
    purpose: "提供乳糖、蛋白与奶香，常用于烘焙、肉制品与糖果。",
    detail: "属乳制品，含乳糖，乳蛋白过敏人群需注意。",
    allergens: ["乳"],
    caution: "含乳糖，乳蛋白过敏人群不宜。",
    audience: "乳糖不耐受、乳蛋白过敏人群应留意。",
    source: "GB 11674 / OFF",
    updatedAt: "2026-09-02",
  },
  乳清: {
    name: "乳清",
    category: "processed",
    oneLiner: "牛乳制奶酪过程中分离出的液体，含乳蛋白与乳糖。",
    processingNature: "加工原料",
    purpose: "提供乳糖与乳蛋白，用于饮料、烘焙等。",
    allergens: ["乳"],
    caution: "含乳糖。",
    audience: "乳糖不耐受、乳蛋白过敏人群应留意。",
    source: "GB 11674 / OFF",
    updatedAt: "2026-09-02",
  },
  酸奶: {
    name: "酸奶",
    category: "natural",
    oneLiner: "牛乳经乳酸菌发酵制成的乳制品。",
    processingNature: "基础原料",
    purpose: "提供乳蛋白、钙与益生菌。",
    allergens: ["乳"],
    caution: "含乳糖（发酵后部分转化），乳蛋白过敏人群不宜。",
    audience: "乳蛋白过敏人群不宜。",
    source: "GB 19302 / OFF",
    updatedAt: "2026-09-02",
  },
  鸡蛋: {
    name: "鸡蛋",
    category: "natural",
    oneLiner: "常见的动物性蛋白原料。",
    processingNature: "基础原料",
    purpose: "提供蛋白质、乳化与起泡作用。",
    allergens: ["蛋"],
    caution: "属常见过敏原，且为生冷制品（如蛋黄酱）需注意保存。",
    audience: "蛋类过敏人群不宜。",
    source: "GB 2749 / OFF",
    updatedAt: "2026-08-31",
  },
  全蛋液: {
    name: "全蛋液",
    category: "natural",
    oneLiner: "巴氏杀菌后的液态鸡蛋。",
    processingNature: "基础原料",
    purpose: "用于烘焙、蛋制品等。",
    allergens: ["蛋"],
    source: "GB 2749 / OFF",
    updatedAt: "2026-08-31",
  },
  蛋黄粉: {
    name: "蛋黄粉",
    category: "processed",
    oneLiner: "喷雾干燥制成的蛋黄粉末。",
    processingNature: "加工原料",
    purpose: "提供蛋香与乳化性，常用于烘焙与蛋黄酱。",
    allergens: ["蛋"],
    source: "GB 2749 / OFF",
    updatedAt: "2026-08-31",
  },
  蛋清粉: {
    name: "蛋清粉",
    category: "processed",
    oneLiner: "喷雾干燥制成的蛋清粉末。",
    processingNature: "加工原料",
    purpose: "提供起泡与凝胶作用，用于烘焙。",
    allergens: ["蛋"],
    source: "GB 2749 / OFF",
    updatedAt: "2026-08-31",
  },
  花生: {
    name: "花生",
    category: "natural",
    oneLiner: "常见坚果类原料。",
    processingNature: "基础原料",
    purpose: "提供油脂、蛋白质与风味。",
    allergens: ["花生"],
    caution: "属高致敏性过敏原，食用需留意。",
    audience: "花生过敏人群应避免。",
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  花生酱: {
    name: "花生酱",
    category: "natural",
    oneLiner: "花生研磨制成的酱料。",
    processingNature: "基础原料",
    purpose: "提供浓郁花生风味与顺滑质地。",
    allergens: ["花生"],
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  芝麻: {
    name: "芝麻",
    aliases: ["白芝麻", "黑芝麻"],
    category: "natural",
    oneLiner: "常见油料与调味籽类。",
    processingNature: "基础原料",
    purpose: "提供香气、油脂与点缀。",
    allergens: ["芝麻"],
    caution: "属常见过敏原。",
    audience: "芝麻过敏人群应避免。",
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  核桃: {
    name: "核桃",
    category: "natural",
    oneLiner: "常见坚果原料。",
    processingNature: "基础原料",
    purpose: "提供油脂与坚果风味。",
    allergens: ["坚果"],
    caution: "属坚果过敏原。",
    audience: "坚果过敏人群应避免。",
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  杏仁: {
    name: "杏仁",
    category: "natural",
    oneLiner: "常见坚果原料。",
    processingNature: "基础原料",
    purpose: "提供坚果香气，用于烘焙与糖果。",
    allergens: ["坚果"],
    caution: "属坚果过敏原。",
    audience: "坚果过敏人群应避免。",
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  腰果: {
    name: "腰果",
    category: "natural",
    oneLiner: "常见坚果原料。",
    processingNature: "基础原料",
    purpose: "提供坚果风味，常用于烘焙与炒菜。",
    allergens: ["坚果"],
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  榛子: {
    name: "榛子",
    category: "natural",
    oneLiner: "常见坚果原料。",
    processingNature: "基础原料",
    purpose: "提供坚果香气，常用于巧克力与烘焙。",
    allergens: ["坚果"],
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  开心果: {
    name: "开心果",
    category: "natural",
    oneLiner: "常见坚果原料。",
    processingNature: "基础原料",
    purpose: "提供坚果风味与翠绿色泽。",
    allergens: ["坚果"],
    source: "GB 19300 / OFF",
    updatedAt: "2026-08-31",
  },
  大豆: {
    name: "大豆",
    category: "natural",
    oneLiner: "常见豆类原料。",
    processingNature: "基础原料",
    purpose: "提供植物蛋白与油脂。",
    allergens: ["大豆"],
    caution: "属常见过敏原。",
    audience: "大豆过敏人群应避免。",
    source: "GB 1352 / OFF",
    updatedAt: "2026-08-31",
  },
  大豆分离蛋白: {
    name: "大豆分离蛋白",
    category: "processed",
    oneLiner: "从大豆中提取的高纯度植物蛋白。",
    processingNature: "加工原料",
    purpose: "提供蛋白与乳化、凝胶作用。",
    allergens: ["大豆"],
    source: "GB 20371 / OFF",
    updatedAt: "2026-08-31",
  },
  大豆蛋白: {
    name: "大豆蛋白",
    category: "processed",
    oneLiner: "以大豆为原料的植物蛋白制品。",
    processingNature: "加工原料",
    purpose: "提供植物蛋白，用于肉制品与植物基食品。",
    allergens: ["大豆"],
    source: "GB 20371 / OFF",
    updatedAt: "2026-08-31",
  },
  豌豆蛋白: {
    name: "豌豆蛋白",
    category: "processed",
    oneLiner: "从豌豆中提取的植物蛋白。",
    processingNature: "加工原料",
    purpose: "提供植物蛋白，常用于植物基食品。",
    source: "OFF",
    updatedAt: "2026-08-31",
  },
  酱油: {
    name: "酱油",
    aliases: ["生抽", "老抽"],
    category: "processed",
    oneLiner: "以大豆、小麦等发酵制成的调味液。",
    processingNature: "加工原料",
    purpose: "提供咸鲜风味与色泽。",
    detail: "生抽咸鲜、老抽上色。可能含大豆与小麦成分。",
    caution: "钠含量较高；可能含大豆与小麦成分。",
    audience: "高血压需限钠人群、大豆或麸质过敏人群应留意。",
    allergens: ["大豆", "麸质（视工艺）"],
    source: "GB 2717 / OFF",
    updatedAt: "2026-08-31",
  },
  蚝油: {
    name: "蚝油",
    category: "processed",
    oneLiner: "以牡蛎汁浓缩制成的鲜味调味酱。",
    processingNature: "加工原料",
    purpose: "提供浓郁鲜味。",
    allergens: ["贝类（可能）"],
    caution: "钠含量较高，可能含贝类成分。",
    audience: "高血压人群、贝类过敏人群应留意。",
    source: "GB 10133 / OFF",
    updatedAt: "2026-08-31",
  },
  豆瓣酱: {
    name: "豆瓣酱",
    category: "processed",
    oneLiner: "以蚕豆或大豆发酵制成的酱料。",
    processingNature: "加工原料",
    purpose: "提供咸鲜辣味，常用于川菜。",
    allergens: ["大豆"],
    source: "GB 2718 / OFF",
    updatedAt: "2026-08-31",
  },
  番茄酱: {
    name: "番茄酱",
    category: "processed",
    oneLiner: "以番茄浓缩制成的酱料。",
    processingNature: "加工原料",
    purpose: "提供番茄酸甜风味。",
    source: "GB/T 14215 / OFF",
    updatedAt: "2026-08-31",
  },
  醋: {
    name: "醋",
    aliases: ["米醋", "陈醋", "白醋"],
    category: "natural",
    oneLiner: "以粮食发酵制成的酸性调味液。",
    processingNature: "基础原料",
    purpose: "提供酸味与风味。",
    detail: "不同原料与工艺的醋风味各异。",
    source: "GB 2719 / OFF",
    updatedAt: "2026-08-31",
  },
  可可粉: {
    name: "可可粉",
    category: "natural",
    oneLiner: "可可豆加工制成的粉末。",
    processingNature: "基础原料",
    purpose: "提供可可风味与色泽。",
    source: "GB/T 20706 / OFF",
    updatedAt: "2026-08-31",
  },
  可可脂: {
    name: "可可脂",
    category: "natural",
    oneLiner: "从可可豆中提取的天然脂肪。",
    processingNature: "基础原料",
    purpose: "决定巧克力的熔点与顺滑口感。",
    source: "GB/T 20707 / OFF",
    updatedAt: "2026-08-31",
  },
  代可可脂: {
    name: "代可可脂",
    category: "processed",
    oneLiner: "用于替代可可脂的植物油脂。",
    processingNature: "加工原料",
    purpose: "熔点与口感接近可可脂，常用于巧克力制品。",
    detail: "产品如标注「代可可脂」，其风味与品质与纯巧克力有差异。",
    source: "GB/T 30767 / OFF",
    updatedAt: "2026-08-31",
  },
  巧克力: {
    name: "巧克力",
    category: "natural",
    oneLiner: "以可可制品与糖等制成的甜食。",
    processingNature: "基础原料",
    purpose: "提供浓郁可可风味。",
    detail: "可能含乳与大豆成分，请以包装标注为准。",
    caution: "含糖与脂肪较高；可能含乳与大豆成分。",
    audience: "乳、大豆过敏人群及控糖人群应留意。",
    allergens: ["乳（可能）", "大豆（可能）"],
    source: "GB/T 19343 / OFF",
    updatedAt: "2026-08-31",
  },
  椰浆: {
    name: "椰浆",
    category: "natural",
    oneLiner: "由椰肉压榨制成的乳状液体。",
    processingNature: "基础原料",
    purpose: "提供椰香与浓郁口感。",
    source: "GB 2716 / OFF",
    updatedAt: "2026-08-31",
  },
  酵母: {
    name: "酵母",
    category: "natural",
    oneLiner: "用于发酵的微生物菌种。",
    processingNature: "基础原料",
    purpose: "产生二氧化碳使面团膨发。",
    caution: "一般人群安全；部分免疫低下人群大量摄入活菌产品需谨慎。",
    audience: "一般无需特别限制。",
    source: "GB 31639 / OFF",
    updatedAt: "2026-08-31",
  },
  香菇: {
    name: "香菇",
    category: "natural",
    oneLiner: "常见的食用菌。",
    processingNature: "基础原料",
    purpose: "提供鲜味与膳食纤维。",
    source: "GB 7096 / OFF",
    updatedAt: "2026-08-31",
  },
  紫菜: {
    name: "紫菜",
    aliases: ["海苔"],
    category: "natural",
    oneLiner: "常见海藻类食材。",
    processingNature: "基础原料",
    purpose: "提供鲜味、碘与膳食纤维。",
    source: "GB 19643 / OFF",
    updatedAt: "2026-08-31",
  },
  鱼糜: {
    name: "鱼糜",
    category: "processed",
    oneLiner: "鱼类去皮去骨后研磨制成的肉糜。",
    processingNature: "加工原料",
    purpose: "用于鱼丸、蟹棒等水产制品。",
    allergens: ["鱼"],
    source: "SC/T 3702 / OFF",
    updatedAt: "2026-08-31",
  },
  鸡肉粉: {
    name: "鸡肉粉",
    category: "processed",
    oneLiner: "鸡肉浓缩干燥制成的粉末。",
    processingNature: "加工原料",
    purpose: "提供鸡肉风味，常用于汤料与调味。",
    source: "OFF",
    updatedAt: "2026-08-31",
  },
  牛肉粉: {
    name: "牛肉粉",
    category: "processed",
    oneLiner: "牛肉浓缩干燥制成的粉末。",
    processingNature: "加工原料",
    purpose: "提供牛肉风味，常用于汤料与调味。",
    source: "OFF",
    updatedAt: "2026-08-31",
  },
};

/** 添加剂知识库 */
export const ADDITIVE_KB: Record<string, AdditiveKnowledge> = {
  山梨酸钾: {
    name: "山梨酸钾",
    insE: "E202",
    type: "防腐剂",
    oneLiner: "一种常用的食品防腐剂，抑制微生物生长。",
    purpose: "抑制部分微生物生长，帮助延长食品保存期。",
    commonUses: "果酱、饮料、调味酱、烘焙食品等。",
    whyAdded: "在法规允许的范围内防止食品变质，延长货架期。",
    safetyNote: "在批准的使用范围和用量内是允许使用的食品添加剂。",
    caution: "按国家标准限量使用；部分人群可能对其敏感。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-28",
  },
  黄原胶: {
    name: "黄原胶",
    insE: "E415",
    type: "增稠剂",
    oneLiner: "一种微生物发酵制得的天然增稠剂。",
    purpose: "增加食品黏稠度，稳定乳液和悬浮体系。",
    commonUses: "沙拉酱、饮料、冰淇淋、无麸质烘焙等。",
    whyAdded: "帮助改善口感质地并防止分层沉淀。",
    safetyNote: "属微生物发酵来源的增稠剂，多国批准使用。",
    caution: "高剂量可能对部分人群有轻泻作用，正常食用量下不常见。",
    audience: "极少人群可能敏感，一般无需特别关注。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-27",
  },
  大豆卵磷脂: {
    name: "大豆卵磷脂",
    insE: "E322",
    type: "乳化剂",
    oneLiner: "从大豆中提取的天然乳化剂。",
    purpose: "帮助油和水均匀混合，改善食品质地。",
    commonUses: "巧克力、烘焙食品、人造奶油、酱料等。",
    whyAdded: "防止油水分离，提升口感顺滑度。",
    safetyNote: "属大豆来源的天然成分，多国批准使用。",
    caution: "大豆过敏人群需留意该成分来源。",
    audience: "大豆过敏人群应特别留意。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-25",
  },
  碳酸钙: {
    name: "碳酸钙",
    insE: "E170",
    type: "营养强化剂",
    oneLiner: "一种钙源营养强化剂。",
    purpose: "补充钙质，也用作膨松剂或抗结剂。",
    commonUses: "谷物制品、饮料、保健食品等。",
    whyAdded: "补充人体所需钙元素，改善营养构成。",
    safetyNote: "食品级碳酸钙广泛用于钙强化。",
    caution: "按法规限量使用，正常食用无显著风险。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 14880 与 GB 2760 规定。",
    source: "GB 1886 / OFF",
    updatedAt: "2026-08-23",
  },
  香兰素: {
    name: "香兰素",
    insE: "E511",
    type: "香精香料",
    oneLiner: "一种广泛使用的食用香料。",
    purpose: "提供香草香气。",
    commonUses: "烘焙、糖果、乳制品、饮料等。",
    whyAdded: "增强食品香气，改善感官体验。",
    safetyNote: "多国批准用作食用香料，允许限量使用。",
    caution: "按法规使用，高浓度可能有刺激性气味。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-22",
  },
  柠檬酸: {
    name: "柠檬酸",
    insE: "E330",
    type: "酸度调节剂",
    oneLiner: "天然存在于柑橘类水果中的有机酸。",
    purpose: "调节酸度、增强风味并起抗氧化协同作用。",
    commonUses: "饮料、果酱、糖果、加工水果等。",
    whyAdded: "平衡甜度、提升清新口感。",
    safetyNote: "食品级柠檬酸广泛安全使用。",
    caution: "极少数人大量摄入后口腔或肠胃不适。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 1886 / OFF",
    updatedAt: "2026-08-26",
  },
  咖啡因: {
    name: "咖啡因",
    insE: "—",
    type: "其他",
    oneLiner: "天然存在于咖啡、茶叶中的生物碱。",
    purpose: "提供提神作用，常添加于功能饮料。",
    commonUses: "能量饮料、可乐、茶饮料等。",
    whyAdded: "提供兴奋作用，是功能饮料的常见添加成分。",
    safetyNote: "按法规限量；对咖啡因敏感人群需注意摄入量。",
    caution: "孕妇、儿童及咖啡因敏感人群应留意。",
    audience: "孕妇、儿童、睡眠障碍人群应留意。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-26",
  },
  苯甲酸钠: {
    name: "苯甲酸钠",
    insE: "E211",
    type: "防腐剂",
    oneLiner: "一种常用于酸性食品的防腐剂。",
    purpose: "抑制微生物生长，延长保存期。",
    commonUses: "饮料、调味酱、果酱、腌制品等。",
    whyAdded: "在酸性环境下抑制细菌和酵母。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "敏感人群大量摄入可能出现不适；按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-24",
  },
  安赛蜜: {
    name: "安赛蜜",
    insE: "E950",
    type: "甜味剂",
    oneLiner: "一种高倍甜度人工甜味剂。",
    purpose: "提供甜味，甜度约为蔗糖的数百倍。",
    commonUses: "无糖饮料、口香糖、甜点、调味品等。",
    whyAdded: "在减少糖分摄入的同时提供甜味。",
    safetyNote: "多国批准使用，规定每日允许摄入量（ADI）。",
    caution: "苯丙酮尿症人群无需担忧（不含苯丙氨酸），但应按限量使用。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 2760 规定范围与限量使用。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-24",
  },
  食用香精: {
    name: "食用香精",
    insE: "—",
    type: "香精香料",
    oneLiner: "用于提供或增强食品风味的复配香料。",
    purpose: "提供特定风味或香气。",
    commonUses: "饮料、糖果、乳制品、烘焙食品等。",
    whyAdded: "增强食品感官品质，帮助产品风味稳定。",
    safetyNote: "依据食品用香精香料使用准则管理。",
    caution: "具体成分多样，敏感人群难以逐一识别。",
    audience: "对香精较敏感人群可留意。",
    usageScope: "依据 GB 2760 相关规定。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-22",
  },
  维生素C: {
    name: "维生素C",
    insE: "E300",
    type: "抗氧化剂",
    oneLiner: "即抗坏血酸，具有抗氧化作用的水溶性维生素。",
    purpose: "防止氧化变质，同时补充维生素C。",
    commonUses: "饮料、肉制品、果酱、强化食品等。",
    whyAdded: "延缓氧化，保持色泽与风味。",
    safetyNote: "广泛使用的抗氧化剂与营养强化剂。",
    caution: "正常食用安全，超量摄入可增加草酸排泄。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 2760 与 GB 14880 规定。",
    source: "GB 1886 / OFF",
    updatedAt: "2026-08-23",
  },
  维生素B6: {
    name: "维生素B6",
    insE: "—",
    type: "营养强化剂",
    oneLiner: "参与蛋白质代谢的水溶性 B 族维生素。",
    purpose: "补充维生素 B6，帮助能量代谢。",
    commonUses: "强化饮料、运动食品、谷物制品等。",
    whyAdded: "满足特定人群的营养需求。",
    safetyNote: "按法规限量使用，过量摄入有神经毒性风险，应遵循限量。",
    caution: "按法规限量使用，避免超量。",
    audience: "一般人群无需特别关注。",
    usageScope: "依据 GB 14880 规定。",
    source: "GB 14880 / OFF",
    updatedAt: "2026-08-23",
  },
  // ===== GB 2760 常见添加剂扩展（本地知识库 L1，命中 0 token）=====
  山梨酸: {
    name: "山梨酸",
    insE: "E200",
    type: "防腐剂",
    oneLiner: "一种常用的食品防腐剂。",
    purpose: "抑制霉菌与酵母，延长食品保存期。",
    commonUses: "饮料、果酱、腌渍食品等。",
    whyAdded: "在酸性条件下抑菌效果好。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  苯甲酸: {
    name: "苯甲酸",
    insE: "E210",
    type: "防腐剂",
    oneLiner: "酸性食品中常用的防腐剂。",
    purpose: "抑制微生物生长，延长保存期。",
    commonUses: "饮料、调味品、果酱等。",
    whyAdded: "在酸性环境下抑制细菌与酵母。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  脱氢乙酸钠: {
    name: "脱氢乙酸钠",
    insE: "E266",
    type: "防腐剂",
    oneLiner: "一种广谱防腐剂。",
    purpose: "抑制霉菌与细菌，常用于焙烤与酱菜。",
    commonUses: "焙烤食品、糕点、酱菜等。",
    whyAdded: "对霉菌与酵母抑制效果较好。",
    safetyNote: "GB 2760-2024 起已删除其在面包、糕点等焙烤食品中的使用，请留意现行规定。",
    caution: "按现行 GB 2760 规定范围与限量使用。",
    audience: "关注食品添加剂的消费者可留意产品执行标准。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  丙酸钙: {
    name: "丙酸钙",
    insE: "E282",
    type: "防腐剂",
    oneLiner: "常用于抑制霉菌的防腐剂。",
    purpose: "抑制霉菌生长，延长焙烤食品保存期。",
    commonUses: "面包、糕点、焙烤食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  乳酸链球菌素: {
    name: "乳酸链球菌素",
    insE: "E234",
    type: "防腐剂",
    oneLiner: "由乳酸链球菌产生的天然抗菌肽。",
    purpose: "抑制部分革兰氏阳性菌，延长保存期。",
    commonUses: "乳制品、肉制品、罐头等。",
    whyAdded: "源自发酵的天然防腐成分。",
    safetyNote: "多国批准使用，按限量添加。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  双乙酸钠: {
    name: "双乙酸钠",
    insE: "E262",
    type: "防腐剂",
    oneLiner: "乙酸钠与乙酸的复合盐，兼具防霉与酸味调节。",
    purpose: "抑制霉菌与细菌，延长保存期。",
    commonUses: "谷物制品、糕点、调味品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  纳他霉素: {
    name: "纳他霉素",
    insE: "E235",
    type: "防腐剂",
    oneLiner: "天然抗真菌剂，常用于表面防腐。",
    purpose: "抑制霉菌与酵母，延长货架期。",
    commonUses: "奶酪表面、发酵肉制品等。",
    safetyNote: "多国批准使用，按限量添加。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  亚硝酸钠: {
    name: "亚硝酸钠",
    insE: "E250",
    type: "防腐剂",
    oneLiner: "肉制品常用的发色剂与防腐剂。",
    purpose: "使肉制品呈粉红色并抑制肉毒杆菌。",
    commonUses: "火腿、腊肠、酱卤肉等。",
    whyAdded: "发色并防腐，是传统肉制品工艺成分。",
    safetyNote: "按限量使用；维生素C等可抑制亚硝胺形成。",
    caution: "与胺类可能生成亚硝胺，务必按标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  阿斯巴甜: {
    name: "阿斯巴甜",
    insE: "E951",
    type: "甜味剂",
    oneLiner: "高倍甜味剂，甜度约为蔗糖的 200 倍。",
    purpose: "在减少糖分摄入的同时提供甜味。",
    commonUses: "无糖饮料、口香糖、酸奶等。",
    whyAdded: "低热量甜味来源。",
    safetyNote: "多国批准使用，规定了每日允许摄入量（ADI）。",
    caution: "苯丙酮尿症患者需避免（含苯丙氨酸）。",
    audience: "苯丙酮尿症人群应特别注意。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  甜蜜素: {
    name: "甜蜜素",
    insE: "E952",
    type: "甜味剂",
    oneLiner: "即环己基氨基磺酸钠，人工甜味剂。",
    purpose: "提供甜味，甜度约为蔗糖的 30~50 倍。",
    commonUses: "蜜饯、饮料、酱腌菜等。",
    safetyNote: "我国按 GB 2760 规定范围与限量使用。",
    caution: "部分国家曾对其安全性存有争议并限制使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  糖精钠: {
    name: "糖精钠",
    insE: "E954",
    type: "甜味剂",
    oneLiner: "最早的人工甜味剂之一。",
    purpose: "提供甜味，甜度约为蔗糖的数百倍。",
    commonUses: "酱腌菜、蜜饯、饮料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  三氯蔗糖: {
    name: "三氯蔗糖",
    insE: "E955",
    type: "甜味剂",
    oneLiner: "由蔗糖氯化制得的高倍甜味剂。",
    purpose: "提供甜味，甜度约为蔗糖的 600 倍，耐热性好。",
    commonUses: "无糖饮料、烘焙、调味品等。",
    whyAdded: "热量低且性质稳定，适合焙烤。",
    safetyNote: "多国批准使用，按限量添加。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  麦芽糖醇: {
    name: "麦芽糖醇",
    insE: "E965",
    type: "甜味剂",
    oneLiner: "糖醇类甜味剂，甜度接近蔗糖。",
    purpose: "提供甜味，热量低于蔗糖。",
    commonUses: "无糖糖果、巧克力、烘焙等。",
    whyAdded: "低热量甜味与保湿作用。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "过量摄入可能引起肠胃不适或腹泻。",
    audience: "对糖醇敏感人群可留意。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  山梨糖醇: {
    name: "山梨糖醇",
    insE: "E420",
    type: "甜味剂",
    oneLiner: "糖醇类甜味剂与保湿剂。",
    purpose: "提供甜味并保持食品湿润。",
    commonUses: "糖果、口香糖、糕点等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "过量摄入可能引起肠胃不适或腹泻。",
    audience: "对糖醇敏感人群可留意。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  木糖醇: {
    name: "木糖醇",
    insE: "E967",
    type: "甜味剂",
    oneLiner: "天然存在于果蔬中的糖醇。",
    purpose: "提供甜味，常用于无糖口香糖。",
    commonUses: "无糖口香糖、糖果等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "人过量摄入可能腹泻；对犬类有毒性，需远离宠物。",
    audience: "对糖醇敏感人群可留意。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  赤藓糖醇: {
    name: "赤藓糖醇",
    insE: "E968",
    type: "甜味剂",
    oneLiner: "天然存在的四碳糖醇，热量极低。",
    purpose: "提供甜味，几乎不产生热量。",
    commonUses: "无糖饮料、烘焙等。",
    whyAdded: "热量低且口感接近蔗糖。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "过量摄入可能引起肠胃不适。",
    audience: "对糖醇敏感人群可留意。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  柠檬黄: {
    name: "柠檬黄",
    insE: "E102",
    type: "着色剂",
    oneLiner: "人工合成黄色着色剂。",
    purpose: "提供黄色色泽。",
    commonUses: "饮料、糖果、果冻、糕点等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "少数人群可能过敏，按限量使用。",
    audience: "对色素敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  日落黄: {
    name: "日落黄",
    insE: "E110",
    type: "着色剂",
    oneLiner: "人工合成橙黄色着色剂。",
    purpose: "提供橙黄色色泽。",
    commonUses: "饮料、糖果、调味酱等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对色素敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  胭脂红: {
    name: "胭脂红",
    insE: "E124",
    type: "着色剂",
    oneLiner: "人工合成红色着色剂。",
    purpose: "提供红色色泽。",
    commonUses: "糖果、饮料、肉制品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "少数人群可能过敏，按限量使用。",
    audience: "对色素敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  苋菜红: {
    name: "苋菜红",
    insE: "E123",
    type: "着色剂",
    oneLiner: "人工合成红色着色剂。",
    purpose: "提供红色色泽。",
    commonUses: "果味饮料、糖果等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对色素敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  亮蓝: {
    name: "亮蓝",
    insE: "E133",
    type: "着色剂",
    oneLiner: "人工合成蓝色着色剂。",
    purpose: "提供蓝色色泽。",
    commonUses: "饮料、糖果、冰淇淋等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对色素敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  焦糖色: {
    name: "焦糖色",
    aliases: ["酱色"],
    insE: "E150",
    type: "着色剂",
    oneLiner: "糖类加热生成的棕色着色剂。",
    purpose: "提供棕褐色泽与焦糖风味。",
    commonUses: "酱油、可乐、醋、烘焙食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  红曲红: {
    name: "红曲红",
    insE: "—",
    type: "着色剂",
    oneLiner: "由红曲霉发酵制得的天然红色素。",
    purpose: "提供红色色泽。",
    commonUses: "肉制品、酱卤制品、腐乳等。",
    whyAdded: "天然来源的红色着色。",
    safetyNote: "多国批准使用的天然着色剂。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  姜黄素: {
    name: "姜黄素",
    insE: "E100",
    type: "着色剂",
    oneLiner: "从姜黄中提取的天然黄色素。",
    purpose: "提供黄色色泽。",
    commonUses: "调味品、糖果、饮料等。",
    safetyNote: "天然来源的着色剂，多国批准使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "β-胡萝卜素": {
    name: "β-胡萝卜素",
    insE: "E160a",
    type: "着色剂",
    oneLiner: "天然类胡萝卜素，可转化为维生素 A。",
    purpose: "提供橙黄色泽并兼具营养强化作用。",
    commonUses: "饮料、黄油、烘焙等。",
    safetyNote: "天然来源，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  辣椒红: {
    name: "辣椒红",
    insE: "—",
    type: "着色剂",
    oneLiner: "从辣椒中提取的天然红色素。",
    purpose: "提供红色色泽。",
    commonUses: "调味酱、肉制品、糕点等。",
    safetyNote: "天然来源的着色剂。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  二氧化钛: {
    name: "二氧化钛",
    insE: "E171",
    type: "着色剂",
    oneLiner: "白色着色剂。",
    purpose: "提供白色色泽与遮盖力。",
    commonUses: "糖果、糕点装饰、包衣等。",
    safetyNote: "欧盟已撤销其食品级使用许可；我国目前按 GB 2760 规定范围与限量使用。",
    caution: "按现行 GB 2760 规定使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  叶绿素铜钠: {
    name: "叶绿素铜钠",
    insE: "E141",
    type: "着色剂",
    oneLiner: "天然叶绿素的铜钠盐。",
    purpose: "提供绿色色泽。",
    commonUses: "糖果、饮料、果冻等。",
    safetyNote: "天然来源衍生的着色剂。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  卡拉胶: {
    name: "卡拉胶",
    insE: "E407",
    type: "增稠剂",
    oneLiner: "从红藻中提取的多糖胶体。",
    purpose: "增稠、凝胶并稳定体系。",
    commonUses: "乳制品、果冻、肉制品、饮料等。",
    safetyNote: "天然来源，多国批准使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  瓜尔胶: {
    name: "瓜尔胶",
    insE: "E412",
    type: "增稠剂",
    oneLiner: "从瓜尔豆中提取的多糖。",
    purpose: "增稠并稳定悬浮体系。",
    commonUses: "酱料、冰淇淋、乳制品等。",
    safetyNote: "天然来源，多国批准使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  琼脂: {
    name: "琼脂",
    insE: "E406",
    type: "增稠剂",
    oneLiner: "从石花菜等红藻提取的胶凝剂。",
    purpose: "形成透明凝胶。",
    commonUses: "果冻、糕点、糖果等。",
    safetyNote: "天然来源，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  果胶: {
    name: "果胶",
    insE: "E440",
    type: "增稠剂",
    oneLiner: "从柑橘皮或苹果渣提取的天然胶体。",
    purpose: "凝胶、增稠并稳定体系。",
    commonUses: "果酱、果冻、酸奶饮品等。",
    safetyNote: "天然来源，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  羧甲基纤维素钠: {
    name: "羧甲基纤维素钠",
    insE: "E466",
    type: "增稠剂",
    oneLiner: "纤维素衍生物，水溶性增稠剂。",
    purpose: "增稠、稳定并防止析水。",
    commonUses: "饮料、冰淇淋、酱料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  海藻酸钠: {
    name: "海藻酸钠",
    insE: "E401",
    type: "增稠剂",
    oneLiner: "从褐藻提取的多糖。",
    purpose: "增稠、凝胶并稳定体系。",
    commonUses: "果冻、冰淇淋、酱料等。",
    safetyNote: "天然来源，多国批准使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  单硬脂酸甘油酯: {
    name: "单硬脂酸甘油酯",
    insE: "E471",
    type: "乳化剂",
    oneLiner: "最常用的食品乳化剂之一。",
    purpose: "帮助油水混合，改善质构。",
    commonUses: "面包、糕点、冰淇淋、人造奶油等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  聚甘油脂肪酸酯: {
    name: "聚甘油脂肪酸酯",
    insE: "E475",
    type: "乳化剂",
    oneLiner: "聚甘油与脂肪酸酯化的乳化剂。",
    purpose: "帮助油水混合，稳定乳液。",
    commonUses: "乳制品、饮料、烘焙等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  蔗糖脂肪酸酯: {
    name: "蔗糖脂肪酸酯",
    insE: "E473",
    type: "乳化剂",
    oneLiner: "蔗糖与脂肪酸合成的乳化剂。",
    purpose: "乳化与稳定体系。",
    commonUses: "乳饮料、冰淇淋、糖果等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  聚山梨醇酯80: {
    name: "聚山梨醇酯80",
    aliases: ["吐温80"],
    insE: "E433",
    type: "乳化剂",
    oneLiner: "合成乳化剂，帮助油水混合。",
    purpose: "乳化并稳定体系。",
    commonUses: "冰淇淋、乳饮料、酱料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  硬脂酰乳酸钠: {
    name: "硬脂酰乳酸钠",
    insE: "E481",
    type: "乳化剂",
    oneLiner: "常用于面团的乳化剂。",
    purpose: "改善面团结构与面包体积。",
    commonUses: "面包、糕点等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "D-异抗坏血酸钠": {
    name: "D-异抗坏血酸钠",
    insE: "E316",
    type: "抗氧化剂",
    oneLiner: "维生素 C 异构体的钠盐。",
    purpose: "防止氧化变色与风味劣变。",
    commonUses: "肉制品、饮料、果酒等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  特丁基对苯二酚: {
    name: "特丁基对苯二酚",
    aliases: ["TBHQ"],
    insE: "E319",
    type: "抗氧化剂",
    oneLiner: "合成抗氧化剂，防止油脂氧化。",
    purpose: "延缓油脂氧化酸败。",
    commonUses: "油炸食品、油脂、坚果制品等。",
    safetyNote: "多国批准使用，按限量添加。",
    caution: "按限量使用；其安全性在国际上有一定讨论。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  丁基羟基茴香醚: {
    name: "丁基羟基茴香醚",
    aliases: ["BHA"],
    insE: "E320",
    type: "抗氧化剂",
    oneLiner: "合成抗氧化剂。",
    purpose: "延缓油脂氧化。",
    commonUses: "油脂、油炸食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  二丁基羟基甲苯: {
    name: "二丁基羟基甲苯",
    aliases: ["BHT"],
    insE: "E321",
    type: "抗氧化剂",
    oneLiner: "合成抗氧化剂。",
    purpose: "延缓油脂氧化。",
    commonUses: "油脂、油炸食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  焦亚硫酸钠: {
    name: "焦亚硫酸钠",
    insE: "E223",
    type: "抗氧化剂",
    oneLiner: "亚硫酸盐类，兼具漂白与防腐作用。",
    purpose: "防止氧化褐变并漂白。",
    commonUses: "果干、果汁、酒类、虾类等。",
    whyAdded: "抑制酶促褐变与微生物。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "哮喘与亚硫酸盐敏感人群需特别留意。",
    audience: "亚硫酸盐敏感人群应留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  没食子酸丙酯: {
    name: "没食子酸丙酯",
    insE: "E310",
    type: "抗氧化剂",
    oneLiner: "合成抗氧化剂，用于油脂。",
    purpose: "延缓油脂氧化。",
    commonUses: "油脂、油炸食品、坚果等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "对食品添加剂较敏感人群可留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  乙二胺四乙酸二钠: {
    name: "乙二胺四乙酸二钠",
    aliases: ["EDTA-2Na"],
    insE: "E385",
    type: "抗氧化剂",
    oneLiner: "金属离子螯合剂，防止氧化变色。",
    purpose: "螯合金属离子，防止氧化与浑浊。",
    commonUses: "饮料、酱料、罐头等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  柠檬酸钠: {
    name: "柠檬酸钠",
    insE: "E331",
    type: "酸度调节剂",
    oneLiner: "柠檬酸的钠盐。",
    purpose: "调节酸度并缓冲 pH。",
    commonUses: "饮料、果冻、乳制品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  乳酸: {
    name: "乳酸",
    insE: "E270",
    type: "酸度调节剂",
    oneLiner: "天然存在于发酵食品中的有机酸。",
    purpose: "调节酸度并抑制微生物。",
    commonUses: "酸奶、饮料、酱料等。",
    safetyNote: "天然来源，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  苹果酸: {
    name: "苹果酸",
    insE: "E296",
    type: "酸度调节剂",
    oneLiner: "存在于水果中的有机酸。",
    purpose: "调节酸度，提供清新酸味。",
    commonUses: "饮料、糖果、果酱等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  酒石酸: {
    name: "酒石酸",
    insE: "E334",
    type: "酸度调节剂",
    oneLiner: "存在于葡萄中的有机酸。",
    purpose: "调节酸度，也用作泡打粉酸性组分。",
    commonUses: "饮料、果冻、烘焙等。",
    safetyNote: "天然来源，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  冰乙酸: {
    name: "冰乙酸",
    aliases: ["醋酸"],
    insE: "E260",
    type: "酸度调节剂",
    oneLiner: "即醋酸，食醋的主要成分。",
    purpose: "调节酸度并抑制微生物。",
    commonUses: "调味品、泡菜、酱菜等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  碳酸氢钠: {
    name: "碳酸氢钠",
    aliases: ["小苏打"],
    insE: "E500",
    type: "膨松剂",
    oneLiner: "即小苏打，遇酸或热释放二氧化碳。",
    purpose: "使面制品膨松。",
    commonUses: "面包、饼干、馒头等。",
    whyAdded: "受热分解释气，形成疏松结构。",
    safetyNote: "广泛使用的食品添加剂与家庭原料。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  碳酸氢铵: {
    name: "碳酸氢铵",
    aliases: ["臭粉"],
    insE: "E503",
    type: "膨松剂",
    oneLiner: "受热分解释放气体的膨松剂。",
    purpose: "使饼干等制品膨松。",
    commonUses: "饼干、薄脆等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  磷酸氢钙: {
    name: "磷酸氢钙",
    insE: "E341",
    type: "膨松剂",
    oneLiner: "膨松剂组分，兼具钙源作用。",
    purpose: "在泡打粉中提供酸性组分与钙。",
    commonUses: "烘焙食品、谷物制品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  酒石酸氢钾: {
    name: "酒石酸氢钾",
    insE: "E336",
    type: "膨松剂",
    oneLiner: "泡打粉中的酸性组分。",
    purpose: "与碳酸氢盐反应产生气体，帮助膨松。",
    commonUses: "烘焙食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "葡萄糖酸-δ-内酯": {
    name: "葡萄糖酸-δ-内酯",
    aliases: ["内酯"],
    insE: "E575",
    type: "凝固剂",
    oneLiner: "内酯豆腐的凝固剂。",
    purpose: "缓慢释放酸使蛋白质凝固。",
    commonUses: "豆腐、豆制品、香肠等。",
    whyAdded: "形成细嫩均一的豆腐质地。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  谷氨酸钠: {
    name: "谷氨酸钠",
    aliases: ["味精"],
    insE: "E621",
    type: "增味剂",
    oneLiner: "即味精，最常用的鲜味剂。",
    purpose: "增强食品鲜味。",
    commonUses: "调味品、方便面、膨化食品等。",
    whyAdded: "提供鲜味，增强风味层次。",
    safetyNote: "我国按 GB 2760 规定范围使用，日常用量下未见明确健康风险。",
    caution: "按国家标准使用；对谷氨酸敏感人群可留意。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "5'-呈味核苷酸二钠": {
    name: "5'-呈味核苷酸二钠",
    insE: "E635",
    type: "增味剂",
    oneLiner: "肌苷酸与鸟苷酸的混合钠盐。",
    purpose: "与谷氨酸钠复配增强鲜味。",
    commonUses: "调味品、汤料、膨化食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "5'-肌苷酸二钠": {
    name: "5'-肌苷酸二钠",
    insE: "E631",
    type: "增味剂",
    oneLiner: "呈鲜味核苷酸。",
    purpose: "与谷氨酸钠复配增强鲜味。",
    commonUses: "调味品、汤料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  "5'-鸟苷酸二钠": {
    name: "5'-鸟苷酸二钠",
    insE: "E627",
    type: "增味剂",
    oneLiner: "呈鲜味核苷酸。",
    purpose: "与谷氨酸钠复配增强鲜味。",
    commonUses: "调味品、汤料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  酵母抽提物: {
    name: "酵母抽提物",
    insE: "—",
    type: "增味剂",
    oneLiner: "以酵母为原料制取的天然风味成分。",
    purpose: "提供鲜味与醇厚风味。",
    commonUses: "调味品、汤料、膨化食品等。",
    whyAdded: "天然鲜味来源，常作为味精替代或协同成分。",
    safetyNote: "天然来源的风味原料。",
    caution: "一般无需特别关注。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  三聚磷酸钠: {
    name: "三聚磷酸钠",
    insE: "E451",
    type: "水分保持剂",
    oneLiner: "多聚磷酸盐，常用于肉制品保水。",
    purpose: "提高肉制品保水性，改善口感。",
    commonUses: "肉制品、水产制品等。",
    whyAdded: "螯合金属离子并提高持水能力。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  六偏磷酸钠: {
    name: "六偏磷酸钠",
    insE: "E452",
    type: "水分保持剂",
    oneLiner: "多聚磷酸盐。",
    purpose: "保水、螯合并稳定体系。",
    commonUses: "肉制品、饮料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  焦磷酸钠: {
    name: "焦磷酸钠",
    insE: "E450",
    type: "水分保持剂",
    oneLiner: "多聚磷酸盐。",
    purpose: "保水、乳化并螯合金属离子。",
    commonUses: "肉制品、水产制品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  氯化钙: {
    name: "氯化钙",
    insE: "E509",
    type: "稳定剂",
    oneLiner: "钙盐稳定剂与凝固剂。",
    purpose: "稳定果冻体系并补充钙质。",
    commonUses: "果冻、豆制品、腌渍食品等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  硫酸钙: {
    name: "硫酸钙",
    aliases: ["石膏"],
    insE: "E516",
    type: "凝固剂",
    oneLiner: "即石膏，传统豆腐凝固剂。",
    purpose: "使豆浆中的蛋白质凝固成豆腐。",
    commonUses: "豆制品、面粉处理等。",
    safetyNote: "传统豆制品凝固剂，广泛安全使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  乳酸钙: {
    name: "乳酸钙",
    insE: "E327",
    type: "稳定剂",
    oneLiner: "钙源兼酸度调节剂。",
    purpose: "补充钙质并稳定体系。",
    commonUses: "果冻、面包、饮料等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  二氧化硫: {
    name: "二氧化硫",
    insE: "E220",
    type: "漂白剂",
    oneLiner: "硫处理剂，兼具漂白与防腐作用。",
    purpose: "漂白、防止褐变并抑制微生物。",
    commonUses: "果干、果酒、果汁等。",
    whyAdded: "保持色泽并延长保存期。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "哮喘与亚硫酸盐敏感人群需特别留意。",
    audience: "亚硫酸盐敏感人群应留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  亚硫酸钠: {
    name: "亚硫酸钠",
    insE: "E221",
    type: "漂白剂",
    oneLiner: "硫处理剂。",
    purpose: "漂白、防腐并防止褐变。",
    commonUses: "果干、腌渍蔬菜等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "哮喘与亚硫酸盐敏感人群需特别留意。",
    audience: "亚硫酸盐敏感人群应留意配料表。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
  碳酸钠: {
    name: "碳酸钠",
    aliases: ["食用碱", "纯碱"],
    insE: "E500",
    type: "膨松剂",
    oneLiner: "即食用碱，弱碱性盐。",
    purpose: "调节酸碱度、使面条等制品筋道。",
    commonUses: "面制品、粽子等。",
    safetyNote: "在批准范围与限量内允许使用。",
    caution: "按国家标准限量使用。",
    audience: "一般人群无需特别关注。",
    source: "GB 2760 / OFF",
    updatedAt: "2026-08-31",
  },
};

/** 按标准名查配料知识 */
export function getIngredientKnowledge(name: string): IngredientKnowledge | undefined {
  return INGREDIENT_KB[name] ?? INGREDIENT_KB[findAlias(name)];
}

/** 按名称查添加剂知识 */
export function getAdditiveKnowledge(name: string): AdditiveKnowledge | undefined {
  return ADDITIVE_KB[name];
}

function findAlias(name: string): string {
  for (const [key, kb] of Object.entries(INGREDIENT_KB)) {
    if (kb.aliases?.includes(name)) return key;
  }
  return name;
}
